"""adicionado campo is_verified a tabela Viajante e excluido campo foto de perfil

Revision ID: 0bc5b79495cd
Revises: 7884190d2861
Create Date: 2025-11-25 17:24:17.403233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc5b79495cd'
down_revision = '7884190d2861'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.drop_column('foto_perfil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
