"""alteração na relação de viagem e atividades

Revision ID: 4d9b8f4114e6
Revises: 0bc5b79495cd
Create Date: 2025-12-09 15:36:23.552719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9b8f4114e6'
down_revision = '0bc5b79495cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_atividade_viagem'), type_='foreignkey')
        batch_op.create_foreign_key('fk_atividade_viagem', 'viagens', ['id_viagem'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.drop_constraint('fk_atividade_viagem', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_atividade_viagem'), 'viagens', ['id_viagem'], ['id'])

    # ### end Alembic commands ###
