"""mudança na tabela Viajante

Revision ID: 7884190d2861
Revises: fe535d63649f
Create Date: 2025-11-21 11:43:10.354271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7884190d2861'
down_revision = 'fe535d63649f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajantes', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viajantes', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
