"""Adiciona valor_restante em Viagem

Revision ID: a86edd82e6cd
Revises: 
Create Date: 2025-10-24 11:00:11.769856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a86edd82e6cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_restante', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viagens', schema=None) as batch_op:
        batch_op.drop_column('valor_restante')

    # ### end Alembic commands ###
