"""Atualiza lógica de Viagem

Revision ID: fe535d63649f
Revises: a86edd82e6cd
Create Date: 2025-10-24 14:59:12.045949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe535d63649f'
down_revision = 'a86edd82e6cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.alter_column('id_viagem',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividades', schema=None) as batch_op:
        batch_op.alter_column('id_viagem',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
